const wishListActionType = {
    TOGGLE_LIST_HIDDEN: 'TOGGLE_LIST_HIDDEN',
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    CLEAR_LIST:'CLEAR_LIST',
    UPDATE_CART_FIREBASE:'UPDATE_CART_FIREBASE',
    SET_CART_FROM_FIREBASE:'SET_CART_FROM_FIREBASE',
};
  
export default wishListActionType;