const BuyActionTypes = {
    BUY_ITEM_START:'BUY_ITEM_START',
    BUY_ITEM_SUCCESS:'BUY_ITEM_SUCCESS',
    BUY_ITEM_FAILURE:'BUY_ITEM_FAILURE',
    CLEAR_BUY_ITEMS:'CLEAR_BUY_ITEMS',
    SET_BUY_ITEMS_FROM_FIREBASE:'SET_BUY_ITEMS_FROM_FIREBASE'
}

export default BuyActionTypes