const StoreActionTypes = {
  FETCH_COLLECTION_START: 'FETCH_COLLECTION_START',
  FETCH_COLLECTION_SUCCESS:'FETCH_COLLECTION_SUCCESS',
  FETCH_COLLECTION_FAILURE:'FETCH_COLLECTION_FAILURE',
  FETCH_PEOPLE_START:'FETCH_PEOPLE_START',
  FETCH_PEOPLE_SUCCESS:'FETCH_PEOPLE_SUCCESS',
  FETCH_PEOPLE_FAILURE:'FETCH_PEOPLE_FAILURE',
  PUSH_USER_COMMENT:'PUSH_USER_COMMENT',
  FETCH_USERS_START:'FETCH_USERS_START',
  FETCH_USERS_SUCCESS:'FETCH_USERS_SUCCESS',
  FETCH_USERS_FAILURE:'FETCH_USERS_FAILURE',
};

export default StoreActionTypes;