const PersonActionTypes = {
    SELECT_PERSON_START:'SELECT_PERSON_START',
    SELECT_PERSON_SUCCESSS:'SELECT_PERSON_SUCCESS',
    SELECT_PERSON_FAILURE:'SELECT_PERSON_FAILURE'
}

export default PersonActionTypes