const ItemActionTypes={
    SELECT_CURRENT_ITEM_START:'SELECT_CURRENT_ITEM_START',
    SELECT_CURRENT_ITEM_SUCCESS:'SELECT_CURRENT_ITEM_SUCCESS',
    SELECT_CURRENT_ITEM_FAILURE:'SELECT_CURRENT_ITEM_FAILURE'
}

export default ItemActionTypes